# Generated by Django 4.2.3 on 2025-01-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
