# Generated by Django 4.2.3 on 2025-01-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_game_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='enrollment',
            field=models.CharField(max_length=50),
        ),
    ]
